### ISSUE TITLE
大哥，求救

### ISSUE THREAD

**Issue by qwker7** [clouduan/WechatGameAutoPlayer#13]
Traceback (most recent call last):
  File "C:/Users/qoyiw/Desktop/WechatGameAutoPlayer/AutoPlayPC.py", line 41, in Play
    scr = get_screenshot()
  File "C:\Users\qoyiw\Desktop\WechatGameAutoPlayer\TimeIt.py", line 6, in wrap
    time_flag = time.perf_counter()
AttributeError: 'module' object has no attribute 'perf_counter'
Error occurred: 
None

**Comment by qwker7** [comment]
在线等
