### ISSUE TITLE
 No module named 'win32api' & 'ImgTools'

### ISSUE THREAD

**Issue by clouduan** [clouduan/WechatGameAutoPlayer#22]
@sewevi 你有没有运行 `pip3 install -r requirements.txt` ，确保 `pywin32`成功安装。
再确定你安装的版本和所使用的版本是不是一样（py2的还是py3的）

**Comment by clouduan** [comment]
@fanghaotianHT 把所有的文件都放在一个文件夹里

**Comment by fanghaotianHT** [comment]
C:\Users\lenovo\AppData\Local\Programs\Python\Python36-32\python.exe C:/Users/lenovo/PycharmProjects/untitled4/AutoPlayPC.py
Traceback (most recent call last):
  File "C:/Users/lenovo/PycharmProjects/untitled4/AutoPlayPC.py", line 2, in <module>
    from pymouse import PyMouse
  File "C:\Users\lenovo\AppData\Local\Programs\Python\Python36-32\lib\site-packages\pymouse\__init__.py", line 92, in <module>
    from windows import PyMouse, PyMouseEvent
ModuleNotFoundError: No module named 'windows'
放在一个文件夹之后这个问题怎么又出现了

**Comment by clouduan** [comment]
苹果的话不清楚，不能点击那就不能用了。可以找一个功能全一点的投屏软件

**Comment by sewevi** [comment]
不好意思打扰了，我是py3。
我已经运行了requirements.txt，还是报错，以下是报错信息。
Traceback (most recent call last):
  File "F:/Language/Pycharm/PyCharm 2018.1.2/WechatGameAutoPlayer-master/AutoPlayPC.py", line 2, in <module>
    from pymouse import PyMouse
  File "F:\Language\Pycharm\PyCharm 2018.1.2\venv\lib\site-packages\pymouse\__init__.py", line 92, in <module>
    from pymouse.windows import PyMouse, PyMouseEvent
  File "F:\Language\Pycharm\PyCharm 2018.1.2\venv\lib\site-packages\pymouse\windows.py", line 23, in <module>
    import pythoncom, pyHook
ModuleNotFoundError: No module named 'pyHook'

我py3的lib里已经有Hook这个库了，但是pycharm却找不到。并且已经将
    from pymouse.windows import PyMouse, PyMouseEvent
这句修改完毕。该如何解决？

**Comment by clouduan** [comment]
@sewevi 建议手动安装一下pyhook，参考这个https://github.com/clouduan/WechatGameAutoPlayer/issues/9#issuecomment-386871337

**Comment by sewevi** [comment]
@clouduan 谢谢，问题出在我设置了两个环境，而默认cmd安装到了默认的python里面， 目前已经解决剩下调试config的数值了，非常感谢。

**Comment by sewevi** [comment]
@clouduan 能运行用的Vysor读取图片时并不清晰，比如有时把+读成-，或者把1读成47等等
是否和手机性能有关？又或者尝试下其他录屏软件较好？

**Comment by clouduan** [comment]
不清晰这个应该和手机有关，我用的一加三清晰度良好。

**Comment by sewevi** [comment]
@clouduan 非常感谢

**Comment by fanghaotianHT** [comment]
除了换手机，还有什么办法可以让图片变清晰？
