### ISSUE TITLE
这是怎么回事///

### ISSUE THREAD

**Issue by liuhuyujunwudi** [clouduan/WechatGameAutoPlayer#24]
Error occurred: 
None
Traceback (most recent call last):
  File "D:/程序/新建文件夹/WechatGameAutoPlayer/AutoPlayPC.py", line 43, in Play
    print(expr,eval(expr))
  File "<string>", line 1
    +1-8--
         ^
SyntaxError: unexpected EOF while parsing

**Comment by clouduan** [comment]
识别错误了，所以出现了EOF的错误，检查config文件里是否设置正确

**Comment by liuhuyujunwudi** [comment]
确认过了没毛病，会不会是投屏的像素问题不能分割数字。。。

**Comment by clouduan** [comment]
如果是这情况，建议可以自己截图重新生成序列值。

**Comment by liuhuyujunwudi** [comment]
嗯嗯嗯？截图生成？我用的一个脚本可以直接测的
