### ISSUE TITLE
运行AutoPlayPC.py 报错是什么情况

### ISSUE THREAD

**Issue by from1996iter** [clouduan/WechatGameAutoPlayer#29]
运行AutoPlayPC.py 报错是什么情况
错误信息如下
D:\python\python.exe C:/Users/Administrator/Desktop/GitHub/WechatGameAutoPlayer-master/AutoPlayPC.py
Traceback (most recent call last):
  File "C:/Users/Administrator/Desktop/GitHub/WechatGameAutoPlayer-master/AutoPlayPC.py", line 2, in <module>
    from pymouse import PyMouse
  File "D:\python\lib\site-packages\pymouse\__init__.py", line 38, in <module>
    from .windows import PyMouse, PyMouseEvent
  File "D:\python\lib\site-packages\pymouse\windows.py", line 17, in <module>
    import win32api
ImportError: DLL load failed: 找不到指定的模块。

**Comment by clouduan** [comment]
先安装 pywin32 
```
pip3 install -r requirements.txt
```
